### ISSUE TITLE
add the ability to choose in the config the file names

### ISSUE THREAD

**Issue by CVarisco** [CVarisco/create-component-app#20]
Adds the ability to the user to insert the file name.
Something like this in the config:

```
{
  ...
  file_name: {
    test: 'COMPONENT_NAME.test.js',
    etc
  }
}
```

thanks to @viktorbergehall

**Comment by iagodahlem** [comment]
Hey @CVarisco, that's a great feature that I will really appreciate. I will try to figure this out and open a PR.

But first, I have some suggestions. What do you think about pass just the prefix used in the file name to config? Like this:

```js
{
  ...
  file_name: {
    test: 'test', //or
    test: 'spec', // or
    etc
  }
}
```

I think this way will be better to deal with the name and extension of the file, and just do something like this to generate the name of the file:

```js
fs.outputFile(`${destination}/${name}.{testPrefix}.${jsExtension}`, generateTestTemplate(name))
```

What do you think?

**Comment by CVarisco** [comment]
Hi @iagodahlem,
thanks to your support 🙂 

What do you think if the user can choose in base the name and the testPrefix ?
Example:

```
{
  ...
  file_name: {
    testPrefix: 'test', //or
    test: 'COMPONENT_NAME',
    etc
  }
}
```

And, what do you think if the user can use the constant `COMPONENT_NAME` to be replaced on the `file_name` config object ?

Example with component name = `MyComponent`
```
{
  ...
  file_name: {
    testPrefix: 'test', //or
    test: 'COMPONENT_NAME',
    component: 'Button',
    etc
  }
}
```
Results:
- Test file: `MyComponent.test.js`
- Component File: `Button.js`

Understand what I mean ?
Thanks again 🌮

**Comment by iagodahlem** [comment]
Hey @CVarisco! I thank you man.

I guess that I get it. So let's see, your idea is, let user pass some optional options to _file_name_ property, being some of this options:

- `testPrefix`: Overrides the match word used on test files, for instance.
- `test`: Overrides the name used on test files.
- `component`: Override the name used on the component file itself.

What do you think? Do you have any other option in mind? Let's try to get and document all possible options that we want to add.

Another suggestions that I have for the options name, tell me what you think:

- `testFileMatch`, instead of `testPrefix`, default value to _test_.
- `testFileName`, instead of `test`, default value to _COMPONENT_NAME_.
- `componentFileName`, instead of `component`, default to _COMPONENT_NAME_.

So we use like this: 

```json
{
  "fileNames": {
    "testFileMatch": "spec"
  }
}
```

**Comment by CVarisco** [comment]
Yeah 🎉 
And also the style file name is a good option to add.

So:

```
{
  "fileNames": {
    "testFileMatch": "spec",
    "testFileName": "myTest",  // default value to COMPONENT_NAME.
    "componentFileName": "component",  // default value to COMPONENT_NAME.
    "styleFileName": "styles", // default to COMPONENT_NAME.
  }
}
``` 

Is it ok for you ?

**Comment by iagodahlem** [comment]
Yes.

That's great to me.

Let's do this. 

:metal: :metal: :metal:

**Comment by CVarisco** [comment]
Hi !

I'm working on it on [filenames-feature](https://github.com/CVarisco/create-component-app/tree/filenames-feature) branch 📇
