### ISSUE TITLE
Proposal: Editor plugins

### ISSUE THREAD

**Issue by blackxored** [CVarisco/create-component-app#35]
I think to make this really useful, editor integrations need to be coded. I realize this is easier said than done given the languages you usually code within these platforms. But I don't think it provides a huge benefit to code snippets without it; or at the very least as much as a better alternative as it could.

**Comment by CVarisco** [comment]
Hi @blackxored !

thanks a lot for your contributions, I appreciate 🙂 
You are right, the editor extension could be a valid way to use this tool.
But there are a lot of editors, and with this tool, I want to prevent to develop the extension for all the editors (with all the problems that you have with the editor limitations and the tool features).
But, I will really happy to help you if you'll write an extension 🙂 

However, the idea that there is only one tool to create a component for me is very helpful because it is independent of the editor that the user uses.
Another important thing is that this tool it is very helpful when you need to work on different projects at the same time, where all the projects have a different way to write components (to me happen a lot of times).

I have a question for you, do you ever try the custom templates feature?
Because if you think that the snippets are a good solution I think that for you could be very useful 🙂 

I hope that I answer a little on why I'm doing this.
Thanks again a lot for your support 🌮

**Comment by tim-soft** [comment]
An atom integration would be pretty handy

**Comment by clemsos** [comment]
@CVarisco : sorry to interfere, but what is the editor used in the README gif demo ?

**Comment by CVarisco** [comment]
Hi @clemsos !

Don’t worry, the editor is Visual studio Code 🤓

**Comment by clemsos** [comment]
thanks ! looks nice :)

**Comment by CVarisco** [comment]
Closed because for now there are no chances to have editor plugins
